baseurl         = ""
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
# SectionPagesMenu = "main"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableEmoji = true

[params]
  title       = "Blog by AbhiiGatty"
  subtitle    = ""

  cover       = "uploads/header_7.jpg"
  description = "Personal blog by AbhiiGatty"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "abhiigatty_"
  fbName = ""
  githubName = "Hitoshirenu"
  linkedinName = "abhiigatty"
  mediumName = "abhiigatty"
  instagramName = "abhiigatty"

  logo = "uploads/logo.png"
  orgName = "AbhiiGatty"
  orgWebsite = "https://www.abhiigatty.com/"
  orgDescription = "Personal blog by AbhiiGatty"

  author = "AbhiiGatty"
  authorAvatar = "uploads/profile/profile_1.jpg"
  authorLocation = "Mangaluru, India"
  authorWebsite = "https://Hitoshirenu.github.io"
  authorDescription = "Perpetual lazy programmer | BlockChain, BigData, WebDev, NetworkSecurity and Biriyani enthusiast"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

# [permalinks]
#   post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Linux"
  url = "/tags/linux/"
  weight = 100

[[menu.main]]
  name = "Tutorials"
  url = "/categories/tutorials/"
  weight = 99

[[menu.main]]
  name = "Resume"
  url = "https://google.com/"
  weight = 95